env:
  global:
    - CI_DIR=.ci_config
  matrix:
    - ROS_DISTRO=indigo
    - ROS_DISTRO=jade
sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
#notifications:
#  Whoever receives success and/or failure via email
before_script:
  - sudo rm -fr /opt/python/
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - source $CI_DIR/travis_before_script.sh
script:
  - source $CI_DIR/travis_npm.sh
